apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d56ez21fi-dotnet-basic
  janus-idp.io/tekton: d56ez21fi-dotnet-basic
  backstage.io/kubernetes-id: d56ez21fi-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d56ez21fi-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
